using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniClub_Hub.Shared.Migrations
{
    /// <inheritdoc />
    public partial class AdoptEventCheckInCodesTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: the EventCheckInCodes table already exists on the Neon dev DB
            // (created by the never-committed 20260704025537_AddEventCheckInCodes migration),
            // so guard on table existence. On Neon this whole block is skipped; on a fresh DB
            // it creates the table + FKs + indexes with the exact EF-convention names.
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = 'EventCheckInCodes'
                    ) THEN
                        CREATE TABLE ""EventCheckInCodes"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""EventRegistrationId"" integer NOT NULL,
                            ""EventId"" integer NOT NULL,
                            ""UserId"" text NOT NULL,
                            ""Code"" text NOT NULL,
                            ""CreatedAt"" timestamp with time zone NOT NULL,
                            CONSTRAINT ""PK_EventCheckInCodes"" PRIMARY KEY (""Id""),
                            CONSTRAINT ""FK_EventCheckInCodes_AspNetUsers_UserId"" FOREIGN KEY (""UserId"")
                                REFERENCES ""AspNetUsers"" (""Id"") ON DELETE RESTRICT,
                            CONSTRAINT ""FK_EventCheckInCodes_EventRegistrations_EventRegistrationId"" FOREIGN KEY (""EventRegistrationId"")
                                REFERENCES ""EventRegistrations"" (""Id"") ON DELETE CASCADE,
                            CONSTRAINT ""FK_EventCheckInCodes_Events_EventId"" FOREIGN KEY (""EventId"")
                                REFERENCES ""Events"" (""Id"") ON DELETE RESTRICT
                        );
                        CREATE INDEX ""IX_EventCheckInCodes_EventId"" ON ""EventCheckInCodes"" (""EventId"");
                        CREATE INDEX ""IX_EventCheckInCodes_EventRegistrationId"" ON ""EventCheckInCodes"" (""EventRegistrationId"");
                        CREATE INDEX ""IX_EventCheckInCodes_UserId"" ON ""EventCheckInCodes"" (""UserId"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "EventCheckInCodes");
        }
    }
}
