export const UEF_MAJORS = [
  'Kinh doanh quốc tế',
  'Công nghệ truyền thông',
  'Luật quốc tế',
  'Logistics và quản lý chuỗi cung ứng',
  'Quan hệ công chúng',
  'Kinh doanh thương mại',
  'Quản trị nhân lực',
  'Quản trị nhà hàng và dịch vụ ăn uống',
  'Quảng cáo',
  'Bất động sản',
  'Quản trị kinh doanh',
  'Luật',
  'Luật kinh tế',
  'Quản trị văn phòng',
  'Truyền thông đa phương tiện',
  'Marketing',
  'Quản trị khách sạn',
  'Quản trị dịch vụ du lịch và lữ hành',
  'Kinh tế quốc tế',
  'Quản trị sự kiện',
  'Khoa học dữ liệu',
  'Kiểm toán',
  'Tài chính - Ngân hàng',
  'Tài chính quốc tế',
  'Công nghệ tài chính',
  'Kế toán',
  'Thương mại điện tử',
  'Công nghệ thông tin',
  'Thiết kế đồ họa',
  'Quan hệ quốc tế',
  'Ngôn ngữ Nhật',
  'Ngôn ngữ Trung Quốc',
  'Ngôn ngữ Anh',
  'Ngôn ngữ Hàn Quốc',
  'Tâm lý học',
] as const
